apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness_test
  name: liveness-test-exec
spec:
  containers:
  - name: my-test
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5   
